### ISSUE TITLE
Graph Overview

### ISSUE THREAD

**Issue by alexdunne** [aengusmcmillin/gatsby-theme-brain#13]
I've replicated Roam's Graph Overview for my own site and wondered if it was something you'd be interested in adding to the `gatsby-theme-brain` project or if it's something best left in user-land.

[Implementation is here](https://github.com/alexdunne/notes/blob/master/src/pages/graph-overview.js) if you're interested.

![gatsby-theme-brain-graph-overview](https://user-images.githubusercontent.com/5383225/80162893-7589a900-85cc-11ea-90f9-8391ceebd155.gif)

**Comment by aengusmcmillin** [comment]
That is awesome! I will take a look at the code. My first instinct is to keep things like this in composable separate themes to avoid pulling in too many dependencies by default, but I don't really know what the standard approach is in Gatsby land.

Going to think about it and spend some time tomorrow looking through other examples. Will get back to you on whether this should go in here, or possibly a separate theme (e.g. something like gatsby-theme-brain-graph).

**Comment by alexdunne** [comment]
Sounds great. This is my first time doing anything with Gatsby so it’s unfamiliar territory for me also.

**Comment by aengusmcmillin** [comment]
So, don't have a firm idea of what is standard here yet, but at least based on https://www.gatsbyjs.org/docs/themes/theme-composition/ it looks like monolithic themes are somewhat recommended until the ecosystem figures out the right approach. And I suppose it will be easier to get adoption of lots of cool features if they are added straight in here!

If you feel like extracting your code into a component and putting up a PR I will review, otherwise I might go ahead and do that sometime in the next few days if that is ok with you. 

And since there are going to be more UI components added in, I will also start looking into setting up Theme UI for easier styling of things.
