### ISSUE TITLE
content.matchAll(...) is not a function

### ISSUE THREAD

**Issue by theianjones** [aengusmcmillin/gatsby-theme-brain#29]
I get this error on Netlify:

```
5:18:07 PM: error "@aengusm/gatsby-theme-brain" threw an error while running the sourceNodes lifecycle:
5:18:07 PM: content.matchAll(...) is not a function or its return value is not iterable
5:18:07 PM: 
5:18:07 PM:   TypeError: content.matchAll(...) is not a function or its return value is not   iterable
```

My netlify set up is relatively simple.. it just runs `gatsby build` and looks at the `public/` directory.

When I run `gatsby build` locally. everything works fine.

[heres a link to my site](https://github.com/theianjones/blog)

Do you have any suggestions?

**Comment by aengusmcmillin** [comment]
This is actually addressed on the readme. The issue is that matchAll requires node 12. You should be able to add an environment variable NODE_VERSION on Netlify, set it to 12, and do a redeploy and it should work.

I need to try and see if there is a way to specify that requirement somewhere in the plugin...
