### ISSUE TITLE
Remove note.title (or make it the actual title)

### ISSUE THREAD

**Issue by mxstbr** [aengusmcmillin/gatsby-theme-brain#8]
The `note.title` node field is set to the slug of the note:

https://github.com/aengusmcmillin/gatsby-theme-brain/blob/21f1dc96e712e1c38a92c1f76675de3fcbc9c9b2/src/source-nodes.js#L30

That is a bit strange, as the slug is clearly not the title of the note 😬 I would expect notes to have an h1 at the top of them that is the title, and that will be rendered by the MDXRenderer anyway, so I would vote to remote the `note.title` property entirely?

**Comment by aravindballa** [comment]
I tried a PR for that #4 
Btw, +1 for removing it entirely.

**Comment by aengusmcmillin** [comment]
I think this is fine but just somewhat unclear code. If you look down in processNotesDirectory you can see that the title is set based on the frontmatter for notes with a backing markdown file. The line you are referring to is purely for the notes generated based on incoming references without a backing file. And because there are these two different options, I think it is at least somewhat valuable having it attached to the note rather than needing the mdx rendering to determine whether it has a frontmatter title or whether it should come from the slug.

I might be misunderstanding though, could you show an example where you think this is giving the wrong result?

**Comment by mxstbr** [comment]
![Screenshot 2020-04-18 at 15 57 13](https://user-images.githubusercontent.com/7525670/79639640-49fe5d00-818d-11ea-8ddb-114a903b8945.png)

Markdown file is `About_these_notes.md`, rendered by the default template. The "About_these_notes" is the default template rendering the note.title, the "About these notes" is the h1 in the markdown. 

Contents:

```
# About these notes

Hi, I’m [Max](https://mxstbr.com)! 👋

These are my [[Evergreen notes]], which I [[Write to think]]. They are written for myself and they contain my opinions and principles. I am sharing these publicly because I strongly believe in [[Work in public]].
```

**Comment by aengusmcmillin** [comment]
Ok, so yeah that is what I would expect. You can see it is generating the title ('About_these_notes') based on the slug (also 'About_these_notes'). The problem is that, in my case, I don't actually give a title to most of my Roam notes in the note itself, so I wanted to have a title be provided by the note query based on the slug or the frontmatter.

The way to solve this for your case would be to override the template to not render the title (not recommended because then you wouldn't have a title for your reference generated pages), or remove the title h1 from your markdown and use frontmatter to assign a title instead.

So in this case you could add at the top of the markdown file: 
```
---
title: "About these notes"
---
```

And if you remove your own in-markdown title it will render properly. I'm not sure if there is a better balance between these two approaches though :/

**Comment by aengusmcmillin** [comment]
I will be working on improving the README today to make a lot of this more clear though. The frontmatter stuff in particular isn't easy to discover.

**Comment by mxstbr** [comment]
Yep, I did override the built-in template and that works fine. 👍 


I had no idea you could provide frontmatter though, in that case the `title` property actually makes a lot of sense! Closing.
