### ISSUE TITLE
outboundReferences could be slugs instead of actual matches

### ISSUE THREAD

**Issue by aravindballa** [aengusmcmillin/gatsby-theme-brain#9]
Can we have slugs in the `outboundReferences` like we have for `inboundReferences`? This would help in fetching content from the outbound links with a few changes to the page query.

I could do this by adding
```js
if(note.outboundReferences) {
  note.outboundReferences = note.outboundReferences.map(ob => nameToSlugMap[ob.toLowerCase()]||ob)
}
```
before creating the brainNote `createNode(brainNoteNode)`.

But it feels hacky.

**Comment by aengusmcmillin** [comment]
That makes sense, should be easy enough, I will go ahead and make this change.

I think today I'm also going to try and add something like outboundReferenceNotes as a child to every note, rather than just a string have the actual BrainNote attached. That should make what you have been doing easier. Instead of needing to do a separate query you can literally get what you need right from there for the outbound references.

**Comment by aravindballa** [comment]
You are awesome! Thanks 
💯
